
#spring.application.name=SUBMISSION-SERVICE

spring:
  application:
    name: "SUBMISSION-SERVICE"
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/task_submission_service
    username: root
    password: 12345678
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update


eureka:
  instance:
    preferIpAddress: true
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8070/eureka/
server:
  port: 5003
